FROM ultralytics/ultralytics:latest

RUN pip install pandas

# RUN addgroup --system --gid 1001 plocania && \
#    adduser --system --uid 1001 --ingroup plocania --home /home/plocania --shell /bin/bash plocania && \
#    chown -R plocania:plocania /home/plocania

WORKDIR /home/plocania

# USER plocania